// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: google/protobuf/type.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(_GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define _GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if _GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <protobuf/_GPBDescriptor.h>
 #import <protobuf/_GPBMessage.h>
 #import <protobuf/_GPBRootObject.h>
#else
 #import "_GPBDescriptor.h"
 #import "_GPBMessage.h"
 #import "_GPBRootObject.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30002
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30002 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class _GPBAny;
@class _GPBEnumValue;
@class _GPBField;
@class _GPBOption;
@class _GPBSourceContext;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum _GPBSyntax

/** The syntax in which a protocol buffer element is defined. */
typedef _GPB_ENUM(_GPBSyntax) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  _GPBSyntax_GPBUnrecognizedEnumeratorValue = k_GPBUnrecognizedEnumeratorValue,
  /** Syntax `proto2`. */
  _GPBSyntax_SyntaxProto2 = 0,

  /** Syntax `proto3`. */
  _GPBSyntax_SyntaxProto3 = 1,
};

_GPBEnumDescriptor *_GPBSyntax_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _GPBSyntax_IsValidValue(int32_t value);

#pragma mark - Enum _GPBField_Kind

/** Basic field types. */
typedef _GPB_ENUM(_GPBField_Kind) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  _GPBField_Kind_GPBUnrecognizedEnumeratorValue = k_GPBUnrecognizedEnumeratorValue,
  /** Field type unknown. */
  _GPBField_Kind_TypeUnknown = 0,

  /** Field type double. */
  _GPBField_Kind_TypeDouble = 1,

  /** Field type float. */
  _GPBField_Kind_TypeFloat = 2,

  /** Field type int64. */
  _GPBField_Kind_TypeInt64 = 3,

  /** Field type uint64. */
  _GPBField_Kind_TypeUint64 = 4,

  /** Field type int32. */
  _GPBField_Kind_TypeInt32 = 5,

  /** Field type fixed64. */
  _GPBField_Kind_TypeFixed64 = 6,

  /** Field type fixed32. */
  _GPBField_Kind_TypeFixed32 = 7,

  /** Field type bool. */
  _GPBField_Kind_TypeBool = 8,

  /** Field type string. */
  _GPBField_Kind_TypeString = 9,

  /** Field type group. Proto2 syntax only, and deprecated. */
  _GPBField_Kind_TypeGroup = 10,

  /** Field type message. */
  _GPBField_Kind_TypeMessage = 11,

  /** Field type bytes. */
  _GPBField_Kind_TypeBytes = 12,

  /** Field type uint32. */
  _GPBField_Kind_TypeUint32 = 13,

  /** Field type enum. */
  _GPBField_Kind_TypeEnum = 14,

  /** Field type sfixed32. */
  _GPBField_Kind_TypeSfixed32 = 15,

  /** Field type sfixed64. */
  _GPBField_Kind_TypeSfixed64 = 16,

  /** Field type sint32. */
  _GPBField_Kind_TypeSint32 = 17,

  /** Field type sint64. */
  _GPBField_Kind_TypeSint64 = 18,
};

_GPBEnumDescriptor *_GPBField_Kind_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _GPBField_Kind_IsValidValue(int32_t value);

#pragma mark - Enum _GPBField_Cardinality

/** Whether a field is optional, required, or repeated. */
typedef _GPB_ENUM(_GPBField_Cardinality) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  _GPBField_Cardinality_GPBUnrecognizedEnumeratorValue = k_GPBUnrecognizedEnumeratorValue,
  /** For fields with unknown cardinality. */
  _GPBField_Cardinality_CardinalityUnknown = 0,

  /** For optional fields. */
  _GPBField_Cardinality_CardinalityOptional = 1,

  /** For required fields. Proto2 syntax only. */
  _GPBField_Cardinality_CardinalityRequired = 2,

  /** For repeated fields. */
  _GPBField_Cardinality_CardinalityRepeated = 3,
};

_GPBEnumDescriptor *_GPBField_Cardinality_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL _GPBField_Cardinality_IsValidValue(int32_t value);

#pragma mark - _GPBTypeRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (_GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c _GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
@interface _GPBTypeRoot : _GPBRootObject
@end

#pragma mark - _GPBType

typedef _GPB_ENUM(_GPBType_FieldNumber) {
  _GPBType_FieldNumber_Name = 1,
  _GPBType_FieldNumber_FieldsArray = 2,
  _GPBType_FieldNumber_OneofsArray = 3,
  _GPBType_FieldNumber_OptionsArray = 4,
  _GPBType_FieldNumber_SourceContext = 5,
  _GPBType_FieldNumber_Syntax = 6,
};

/**
 * A protocol buffer message type.
 **/
@interface _GPBType : _GPBMessage

/** The fully qualified message name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** The list of fields. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBField*> *fieldsArray;
/** The number of items in @c fieldsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger fieldsArray_Count;

/** The list of types appearing in `oneof` definitions in this type. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<NSString*> *oneofsArray;
/** The number of items in @c oneofsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger oneofsArray_Count;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) _GPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) _GPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c _GPBType's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t _GPBType_Syntax_RawValue(_GPBType *message);
/**
 * Sets the raw value of an @c _GPBType's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Set_GPBType_Syntax_RawValue(_GPBType *message, int32_t value);

#pragma mark - _GPBField

typedef _GPB_ENUM(_GPBField_FieldNumber) {
  _GPBField_FieldNumber_Kind = 1,
  _GPBField_FieldNumber_Cardinality = 2,
  _GPBField_FieldNumber_Number = 3,
  _GPBField_FieldNumber_Name = 4,
  _GPBField_FieldNumber_TypeURL = 6,
  _GPBField_FieldNumber_OneofIndex = 7,
  _GPBField_FieldNumber_Packed = 8,
  _GPBField_FieldNumber_OptionsArray = 9,
  _GPBField_FieldNumber_JsonName = 10,
  _GPBField_FieldNumber_DefaultValue = 11,
};

/**
 * A single field of a message type.
 **/
@interface _GPBField : _GPBMessage

/** The field type. */
@property(nonatomic, readwrite) _GPBField_Kind kind;

/** The field cardinality. */
@property(nonatomic, readwrite) _GPBField_Cardinality cardinality;

/** The field number. */
@property(nonatomic, readwrite) int32_t number;

/** The field name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The field type URL, without the scheme, for message or enumeration
 * types. Example: `"type.googleapis.com/google.protobuf.Timestamp"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *typeURL;

/**
 * The index of the field type in `Type.oneofs`, for message or enumeration
 * types. The first type has index 1; zero means the type is not in the list.
 **/
@property(nonatomic, readwrite) int32_t oneofIndex;

/** Whether to use alternative packed wire representation. */
@property(nonatomic, readwrite) BOOL packed;

/** The protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The field JSON name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *jsonName;

/** The string value of the default value of this field. Proto2 syntax only. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *defaultValue;

@end

/**
 * Fetches the raw value of a @c _GPBField's @c kind property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t _GPBField_Kind_RawValue(_GPBField *message);
/**
 * Sets the raw value of an @c _GPBField's @c kind property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Set_GPBField_Kind_RawValue(_GPBField *message, int32_t value);

/**
 * Fetches the raw value of a @c _GPBField's @c cardinality property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t _GPBField_Cardinality_RawValue(_GPBField *message);
/**
 * Sets the raw value of an @c _GPBField's @c cardinality property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Set_GPBField_Cardinality_RawValue(_GPBField *message, int32_t value);

#pragma mark - _GPBEnum

typedef _GPB_ENUM(_GPBEnum_FieldNumber) {
  _GPBEnum_FieldNumber_Name = 1,
  _GPBEnum_FieldNumber_EnumvalueArray = 2,
  _GPBEnum_FieldNumber_OptionsArray = 3,
  _GPBEnum_FieldNumber_SourceContext = 4,
  _GPBEnum_FieldNumber_Syntax = 5,
};

/**
 * Enum type definition.
 **/
@interface _GPBEnum : _GPBMessage

/** Enum type name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value definitions. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBEnumValue*> *enumvalueArray;
/** The number of items in @c enumvalueArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger enumvalueArray_Count;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

/** The source context. */
@property(nonatomic, readwrite, strong, null_resettable) _GPBSourceContext *sourceContext;
/** Test to see if @c sourceContext has been set. */
@property(nonatomic, readwrite) BOOL hasSourceContext;

/** The source syntax. */
@property(nonatomic, readwrite) _GPBSyntax syntax;

@end

/**
 * Fetches the raw value of a @c _GPBEnum's @c syntax property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t _GPBEnum_Syntax_RawValue(_GPBEnum *message);
/**
 * Sets the raw value of an @c _GPBEnum's @c syntax property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void Set_GPBEnum_Syntax_RawValue(_GPBEnum *message, int32_t value);

#pragma mark - _GPBEnumValue

typedef _GPB_ENUM(_GPBEnumValue_FieldNumber) {
  _GPBEnumValue_FieldNumber_Name = 1,
  _GPBEnumValue_FieldNumber_Number = 2,
  _GPBEnumValue_FieldNumber_OptionsArray = 3,
};

/**
 * Enum value definition.
 **/
@interface _GPBEnumValue : _GPBMessage

/** Enum value name. */
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/** Enum value number. */
@property(nonatomic, readwrite) int32_t number;

/** Protocol buffer options. */
@property(nonatomic, readwrite, strong, null_resettable) NSMutableArray<_GPBOption*> *optionsArray;
/** The number of items in @c optionsArray without causing the array to be created. */
@property(nonatomic, readonly) NSUInteger optionsArray_Count;

@end

#pragma mark - _GPBOption

typedef _GPB_ENUM(_GPBOption_FieldNumber) {
  _GPBOption_FieldNumber_Name = 1,
  _GPBOption_FieldNumber_Value = 2,
};

/**
 * A protocol buffer option, which can be attached to a message, field,
 * enumeration, etc.
 **/
@interface _GPBOption : _GPBMessage

/**
 * The option's name. For protobuf built-in options (options defined in
 * descriptor.proto), this is the short name. For example, `"map_entry"`.
 * For custom options, it should be the fully-qualified name. For example,
 * `"google.api.http"`.
 **/
@property(nonatomic, readwrite, copy, null_resettable) NSString *name;

/**
 * The option's value packed in an Any message. If the value is a primitive,
 * the corresponding wrapper type defined in google/protobuf/wrappers.proto
 * should be used. If the value is an enum, it should be stored as an int32
 * value using the google.protobuf.Int32Value type.
 **/
@property(nonatomic, readwrite, strong, null_resettable) _GPBAny *value;
/** Test to see if @c value has been set. */
@property(nonatomic, readwrite) BOOL hasValue;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
