platform :ios, '8.0'

target 'Example_Objc' do

  use_frameworks!

  inhibit_all_warnings!

  pod 'CocoaDebug', :path=> '../../CocoaDebug', :configurations => ['Debug'], :inhibit_warnings => true

end
