# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'Example_Swift' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Example_Swift
  pod 'CocoaDebug', :path=> '../../CocoaDebug', :configurations => ['Debug']
  
  target 'Example_SwiftTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
