#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)
#ifndef COCOADEBUG_SWIFT_H
#define COCOADEBUG_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CocoaDebug",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIViewController;

SWIFT_CLASS("_TtC10CocoaDebug10CocoaDebug")
@interface CocoaDebug : NSObject
/// if the crawled URLs contain server URL ,set these URLs bold font to be marked. not mark when this value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable serverURL;)
+ (NSString * _Nullable)serverURL SWIFT_WARN_UNUSED_RESULT;
+ (void)setServerURL:(NSString * _Nullable)value;
/// set the URLs which should not crawled, ignoring case, crawl all URLs when the value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable ignoredURLs;)
+ (NSArray<NSString *> * _Nullable)ignoredURLs SWIFT_WARN_UNUSED_RESULT;
+ (void)setIgnoredURLs:(NSArray<NSString *> * _Nullable)value;
/// set the URLs which are only crawled, ignoring case, crawl all URLs when the value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable onlyURLs;)
+ (NSArray<NSString *> * _Nullable)onlyURLs SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnlyURLs:(NSArray<NSString *> * _Nullable)value;
/// set controllers to be added as child controllers of UITabBarController. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<UIViewController *> * _Nullable tabBarControllers;)
+ (NSArray<UIViewController *> * _Nullable)tabBarControllers SWIFT_WARN_UNUSED_RESULT;
+ (void)setTabBarControllers:(NSArray<UIViewController *> * _Nullable)value;
/// the maximum count of logs which CocoaDebug display. default value is <code>1000</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger logMaxCount;)
+ (NSInteger)logMaxCount SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogMaxCount:(NSInteger)value;
/// set the initial recipients to include in the email’s “To” field when share via email. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable emailToRecipients;)
+ (NSArray<NSString *> * _Nullable)emailToRecipients SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmailToRecipients:(NSArray<NSString *> * _Nullable)value;
/// set the initial recipients to include in the email’s “Cc” field when share via email. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable emailCcRecipients;)
+ (NSArray<NSString *> * _Nullable)emailCcRecipients SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmailCcRecipients:(NSArray<NSString *> * _Nullable)value;
/// set the main color with hexadecimal format. default value is <code>#42d459</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull mainColor;)
+ (NSString * _Nonnull)mainColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setMainColor:(NSString * _Nonnull)value;
/// protobuf url and response class transfer map. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable protobufTransferMap;)
+ (NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable)protobufTransferMap SWIFT_WARN_UNUSED_RESULT;
+ (void)setProtobufTransferMap:(NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable)value;
+ (void)enable;
+ (void)disable;
+ (void)hideBubble;
+ (void)showBubble;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10CocoaDebug18CocoaDebugSettings")
@interface CocoaDebugSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CocoaDebugSettings * _Nonnull shared;)
+ (CocoaDebugSettings * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isRunning;
@property (nonatomic) BOOL slowAnimations;
@property (nonatomic) BOOL responseShake;
@property (nonatomic, copy) NSString * _Nullable firstIn;
@property (nonatomic) BOOL disableCrashRecording;
@property (nonatomic) BOOL enableWebViewMonitoring;
@property (nonatomic) BOOL disableLogMonitoring;
@property (nonatomic) BOOL disableNetworkMonitoring;
@property (nonatomic) BOOL visible;
@property (nonatomic) BOOL showBubbleAndWindow;
@property (nonatomic, copy) NSString * _Nullable serverURL;
@property (nonatomic) NSInteger tabBarSelectItem;
@property (nonatomic) NSInteger logSelectIndex;
@property (nonatomic) NSInteger networkLastIndex;
@property (nonatomic) float bubbleFrameX;
@property (nonatomic) float bubbleFrameY;
@property (nonatomic, copy) NSString * _Nullable logSearchWordDefault;
@property (nonatomic, copy) NSString * _Nullable logSearchWordColor;
@property (nonatomic, copy) NSString * _Nullable logSearchWordH5;
@property (nonatomic, copy) NSString * _Nullable networkSearchWord;
@property (nonatomic, copy) NSString * _Nonnull mainColor;
@property (nonatomic, copy) NSArray<UIViewController *> * _Nullable tabBarControllers;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable emailToRecipients;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable emailCcRecipients;
@property (nonatomic) NSInteger logMaxCount;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable onlyURLs;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable ignoredURLs;
@property (nonatomic, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable protobufTransferMap;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class UIEvent;

@interface UIWindow (SWIFT_EXTENSION(CocoaDebug))
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)motionBegan:(UIEventSubtype)motion withEvent:(UIEvent * _Nullable)event;
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_CLASS("_TtC10CocoaDebug10_LogHelper")
@interface _LogHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10CocoaDebug13_WindowHelper")
@interface _WindowHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__ARM_ARCH_7A__) && __ARM_ARCH_7A__
// Generated by Apple Swift version 5.3 (swiftlang-1200.0.22.4 clang-1200.0.25.1)
#ifndef COCOADEBUG_SWIFT_H
#define COCOADEBUG_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <Foundation/Foundation.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...)
# endif
#endif

#if __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if __has_attribute(objc_method_family)
# define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
#else
# define SWIFT_METHOD_FAMILY(X)
#endif
#if __has_attribute(noescape)
# define SWIFT_NOESCAPE __attribute__((noescape))
#else
# define SWIFT_NOESCAPE
#endif
#if __has_attribute(ns_consumed)
# define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
#else
# define SWIFT_RELEASES_ARGUMENT
#endif
#if __has_attribute(warn_unused_result)
# define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
#else
# define SWIFT_WARN_UNUSED_RESULT
#endif
#if __has_attribute(noreturn)
# define SWIFT_NORETURN __attribute__((noreturn))
#else
# define SWIFT_NORETURN
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if defined(__has_attribute) && __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility)
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if __has_feature(attribute_diagnose_if_objc)
# define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
#else
# define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
#endif
#if !defined(IBSegueAction)
# define IBSegueAction
#endif
#if __has_feature(modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import ObjectiveC;
@import UIKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CocoaDebug",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

@class UIViewController;

SWIFT_CLASS("_TtC10CocoaDebug10CocoaDebug")
@interface CocoaDebug : NSObject
/// if the crawled URLs contain server URL ,set these URLs bold font to be marked. not mark when this value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nullable serverURL;)
+ (NSString * _Nullable)serverURL SWIFT_WARN_UNUSED_RESULT;
+ (void)setServerURL:(NSString * _Nullable)value;
/// set the URLs which should not crawled, ignoring case, crawl all URLs when the value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable ignoredURLs;)
+ (NSArray<NSString *> * _Nullable)ignoredURLs SWIFT_WARN_UNUSED_RESULT;
+ (void)setIgnoredURLs:(NSArray<NSString *> * _Nullable)value;
/// set the URLs which are only crawled, ignoring case, crawl all URLs when the value is nil. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable onlyURLs;)
+ (NSArray<NSString *> * _Nullable)onlyURLs SWIFT_WARN_UNUSED_RESULT;
+ (void)setOnlyURLs:(NSArray<NSString *> * _Nullable)value;
/// set controllers to be added as child controllers of UITabBarController. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<UIViewController *> * _Nullable tabBarControllers;)
+ (NSArray<UIViewController *> * _Nullable)tabBarControllers SWIFT_WARN_UNUSED_RESULT;
+ (void)setTabBarControllers:(NSArray<UIViewController *> * _Nullable)value;
/// the maximum count of logs which CocoaDebug display. default value is <code>1000</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class) NSInteger logMaxCount;)
+ (NSInteger)logMaxCount SWIFT_WARN_UNUSED_RESULT;
+ (void)setLogMaxCount:(NSInteger)value;
/// set the initial recipients to include in the email’s “To” field when share via email. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable emailToRecipients;)
+ (NSArray<NSString *> * _Nullable)emailToRecipients SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmailToRecipients:(NSArray<NSString *> * _Nullable)value;
/// set the initial recipients to include in the email’s “Cc” field when share via email. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSArray<NSString *> * _Nullable emailCcRecipients;)
+ (NSArray<NSString *> * _Nullable)emailCcRecipients SWIFT_WARN_UNUSED_RESULT;
+ (void)setEmailCcRecipients:(NSArray<NSString *> * _Nullable)value;
/// set the main color with hexadecimal format. default value is <code>#42d459</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSString * _Nonnull mainColor;)
+ (NSString * _Nonnull)mainColor SWIFT_WARN_UNUSED_RESULT;
+ (void)setMainColor:(NSString * _Nonnull)value;
/// protobuf url and response class transfer map. default value is <code>nil</code>.
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable protobufTransferMap;)
+ (NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable)protobufTransferMap SWIFT_WARN_UNUSED_RESULT;
+ (void)setProtobufTransferMap:(NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable)value;
+ (void)enable;
+ (void)disable;
+ (void)hideBubble;
+ (void)showBubble;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



SWIFT_CLASS("_TtC10CocoaDebug18CocoaDebugSettings")
@interface CocoaDebugSettings : NSObject
SWIFT_CLASS_PROPERTY(@property (nonatomic, class, readonly, strong) CocoaDebugSettings * _Nonnull shared;)
+ (CocoaDebugSettings * _Nonnull)shared SWIFT_WARN_UNUSED_RESULT;
@property (nonatomic) BOOL isRunning;
@property (nonatomic) BOOL slowAnimations;
@property (nonatomic) BOOL responseShake;
@property (nonatomic, copy) NSString * _Nullable firstIn;
@property (nonatomic) BOOL disableCrashRecording;
@property (nonatomic) BOOL enableWebViewMonitoring;
@property (nonatomic) BOOL disableLogMonitoring;
@property (nonatomic) BOOL disableNetworkMonitoring;
@property (nonatomic) BOOL visible;
@property (nonatomic) BOOL showBubbleAndWindow;
@property (nonatomic, copy) NSString * _Nullable serverURL;
@property (nonatomic) NSInteger tabBarSelectItem;
@property (nonatomic) NSInteger logSelectIndex;
@property (nonatomic) NSInteger networkLastIndex;
@property (nonatomic) float bubbleFrameX;
@property (nonatomic) float bubbleFrameY;
@property (nonatomic, copy) NSString * _Nullable logSearchWordDefault;
@property (nonatomic, copy) NSString * _Nullable logSearchWordColor;
@property (nonatomic, copy) NSString * _Nullable logSearchWordH5;
@property (nonatomic, copy) NSString * _Nullable networkSearchWord;
@property (nonatomic, copy) NSString * _Nonnull mainColor;
@property (nonatomic, copy) NSArray<UIViewController *> * _Nullable tabBarControllers;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable emailToRecipients;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable emailCcRecipients;
@property (nonatomic) NSInteger logMaxCount;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable onlyURLs;
@property (nonatomic, copy) NSArray<NSString *> * _Nullable ignoredURLs;
@property (nonatomic, copy) NSDictionary<NSString *, NSArray<NSString *> *> * _Nullable protobufTransferMap;
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end




@class UIEvent;

@interface UIWindow (SWIFT_EXTENSION(CocoaDebug))
@property (nonatomic, readonly) BOOL canBecomeFirstResponder;
- (void)motionBegan:(UIEventSubtype)motion withEvent:(UIEvent * _Nullable)event;
- (void)motionEnded:(UIEventSubtype)motion withEvent:(UIEvent * _Nullable)event;
@end


SWIFT_CLASS("_TtC10CocoaDebug10_LogHelper")
@interface _LogHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC10CocoaDebug13_WindowHelper")
@interface _WindowHelper : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#pragma clang diagnostic pop
#endif

#endif
